### ISSUE TITLE
the third section bug bookdown

### ISSUE THREAD

**Issue by Rich-010** [tidymodels/TMwR#75] opened 2020-09-29 02:16 UTC
The third section of the bookdown doesn´t have a moving arrow, is just formatting with the bookdown, the user can´t go backwards or forward
![image](https://user-images.githubusercontent.com/71851629/94505022-cd59bb00-01cf-11eb-943e-2325b942356a.png)

**Comment by juliasilge** [comment] 2020-09-29 02:47
@dcossyleon could you take a look at this when you get a chance? It looks like the last chapters of each section (like chapters 3, 9, 15) are missing the navigation arrows for forward/back. Do you think this is fixable?

**Comment by dcossyleon** [comment] 2020-09-29 03:41
@juliasilge This is the same problem as https://github.com/tidymodels/TMwR/issues/40#issuecomment-677955096 that we weren't able to resolve. Something is breaking the HTML for those book sections, but it wasn't the CSS or anything specific about the .Rmd files for those chapters. Unfortunately, I'm not sure what a good fix for this is :-(

**Comment by juliasilge** [comment] 2020-09-29 14:27
Ah right, this is coming back to me now. Thank you! 🙏 

I'm adding this here from your previous comment for context:

> The last chapters in each "part" of the book are the ones that are breaking (so here that's ch. 3, 9, and 16). The problem is that the HTML tag for the `<div class="page-inner">` is closing before it closes in other chapters. The end result is that it breaks the refs, the footnotes, and also the navigation (gray arrows on sides of pages).

I'm going to leave this open as a bug so we can track it, and see if some change to bookdown or something in the future can address it.

**Comment by topepo** [comment] 2020-10-05 22:57
@cderv Hadley said that you might know the solution to this issue.

**Comment by cderv** [comment] 2020-10-06 08:30
I have a looked a bit into this. There is definitly something with the splitting of html by bookdown that throws things off for last Rmd of a PART. 

I need to be able to reproduce too look deeper. Right now, I don't know what is causing this. I understant you have a fix for your book using CSS right ?

**Comment by juliasilge** [comment] 2020-10-06 15:26
@dcossyleon fixed up a bit of CSS for the references and footnotes but we don't have a CSS fix for the navigation.

I believe that everything is in this repo to build the book; I think it must be, for [GH actions](https://github.com/tidymodels/TMwR/blob/master/.github/workflows/bookdown.yaml) to be able to build it and then deploy to Netlify. If there is something specific that errored out @cderv we would love to know about it so we can fix the instructions in the README!

**Comment by cderv** [comment] 2020-10-06 16:56
For example you are directly using `doMC` and that don't work on Windows. So currently, I don't think any standard windows user can rebuild your book. You may want to precise that in your README. 

However, I'll set up my linux env on WSL to make it work on ubuntu locally and I'll look deeper into it. 

Other issue I had was with `affy` 📦  not reported in DESCRIPTION, but that is because it is in extra I guess and because I use `renv::dependencies()` to get all the env. I will go with `remotes::install_deps` or `remotes::install_github()` next time. 

Idea if your want to promote reproducing the book: set up a project on RStudio cloud to copy ?

**Comment by cderv** [comment] 2020-10-12 12:38
Ok I have identified what is causing the issue here. 
You are using some PART header to divide the book and those headers are in their own files

* `basic.Rmd`
* `tools.Rmd`
* `appendix.Rmd`

Those files contain only 
```md
# (PART\*) Title {-} 

```
(Appendix is a special PART header)

I guess this is causing the splitting to go wrong, leading to the previous chapter to not be correctly splitted by **bookdown**

I'll see how easy (or not) it is to support this in **bookdown** - this being having a Rmd file to only define the special PART header. 

Currently, from [special header documentation](https://bookdown.org/yihui/bookdown/markdown-extensions-by-bookdown.html#special-headers), 

> A part title should be written right before the first chapter title in this part.

Having it in another file does not seem to play nice here.

One workaround in the meantime is to put the PART title in the file with the first header. So `ames.Rmd`, `resampling.Rmd`, and `pre-proc-table.Rmd`. 

From my test on your book, this will fix the arrow disappearance and the Reference position and style at the end of the page.

**Comment by juliasilge** [comment] 2020-10-13 15:38
Thank you so much @cderv for digging into this! 🙌  I just set up that workaround.

**Closed** 2020-10-16 02:49 UTC
Labels: bug
