### ISSUE TITLE
Error while trying to render chapter 14

### ISSUE THREAD

**Issue by davidrsch** [tidymodels/TMwR#362] opened 2023-04-15 15:46 UTC
# Error while trying to render chapter 14

Hi, I get the following error message while trying to render chapter 14:

```r
Error in `verify_consistent_sa()`:
! These simulated annealing results don't match the previous values.:
Component “cost”: Mean relative difference: 1.203
Component “mean”: Mean relative difference: 0.01178
Backtrace:
 1. global verify_consistent_sa(collect_metrics(svm_sa_sshh$result))
```

I already run chunk by chunk and confirm that line is the one causing the error, line 797 of 14-iterative-search.Rmd file.

## Addition

I thought it might be related to the necessary use of a developer version of any of the needed packages. I try running the following code to install what I need to create the book (As stated in the description):

```r
remotes::install_github("tidymodels/TMwR")
```

But get the error:
```r
Downloading GitHub repo tidymodels/TMwR@HEAD
Error in utils::download.file(url, path, method = method, quiet = quiet,  : 
  download from 'https://api.github.com/repos/tidymodels/TMwR/tarball/HEAD' failed
```
I am guessing this is due to in this repository is only the book and no the necessary packages.

### Thanks for the work done

**Comment by juliasilge** [comment] 2023-04-17 18:00
Yep, I also have had problems rendering that chapter locally on my development machine, which is a new-ish Mac with an ARM chip. We have focused on building this book [reproducibly via GH actions](https://github.com/tidymodels/TMwR/actions/workflows/bookdown.yaml) on Ubuntu (Intel chip) and haven't prioritized making sure everyone gets exactly the same numerical results on different platforms. Do you have specific concerns or questions about how it is not rendering for you? FWIW the [`verify_consistent_sa()` function](https://github.com/tidymodels/TMwR/blob/main/extras/verify_results.R) is just checking that simulated annealing results haven't changed from what is checked in to the repo.

I wasn't able to reproduce your problem with using `remotes::install_github("tidymodels/TMwR")` (it worked for me) but again, I don't think that's the real problem here; I think the issue is with numerical differences across platforms.

**Comment by davidrsch** [comment] 2023-04-17 19:17
Then to be able to render the chapter and the rest of the book, would be fine if I comment that line?. 

In addition. What update function is used in the 13 and 14 chapter? I recive an error message that there is conflict between `Matrix::update() ` and `recipes::update() `

**Comment by juliasilge** [comment] 2023-04-17 22:28
Depending on your use case (rendering for your own learning?), yes, I would just comment out the line where the simulated annealing results are compared.

There was a recent change to, we believe, Matrix that has required some changes to `tidymodels_prefer()`. You can either comment out the uses of `tidymodels_prefer()` or install a fork of the tidymodels metapackage where this is addressed via `remotes::install_github("tidymodels/tidymodels@conflict-update")`.

**Comment by davidrsch** [comment] 2023-04-21 21:26
Thanks, commenting the line solve the issue on rendering the chapter 14. Although I was unable to render the chapter 15 and the rest of the book, my pc is not very much up to date and after five hours just stop working :sweat_smile:.
I would like to know if there are any plans to make this book more easy to render. Maybe loading results from a folder in the repository instead of executing long time running chunks code. And the user will only have to pull branches whenever changes are made in those chunks code and in the corresponding results.

**Comment by juliasilge** [comment] 2023-04-22 16:38
So FYI it [takes 3.5 to 4 hrs](https://github.com/tidymodels/TMwR/actions/workflows/bookdown.yaml) to render the book on GH actions; we have chosen to prioritize reproducibility (we can render the whole book, with all important models retrained) over priorities around making the book easy or quick to render (where we wouldn't actually retrain models). That aligns best with our goals for how we build this book and we don't think individual readers rendering the whole book is a common desire/need, so unfortunately I'm going to have to say that no, we aren't planning on changes in that direction. We appreciate you reading and your feedback, and hope that you can find what you are hoping to learn with the resources as they are now!

**Comment by juliasilge** [comment] 2023-09-25 19:44
Thanks for your thoughts @davidrsch and let us know if you have further questions!

**Closed by juliasilge** 2023-09-25 19:44 UTC
